[book]
authors = ["Omid Bodaghi"]
language = "en"
multilingual = false
src = "src"
title = "My notes on zkp"

[output.html]
mathjax-support = true
smart-punctuation = true
git-repository-url = "https://github.com/omiboxyz/zkp"

[preprocessor.katex]
